include: package:flutter_lints/flutter.yaml

# cf https://github.com/dart-lang/dart_style/wiki/Configuration
formatter:
  page_width: 240
  trailing_commas: preserve

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
