name: flutter_localizations_plus
description: Localization package for Flutter to support locales not already supported by `flutter_localizations`.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_lints:

flutter:
